version: '2'


services:
  test:
    build: .
    volumes:
      - './tests:/home/app/tests:ro'
      - './test.sh:/home/app/test.sh:ro'
    env_file: ./dev.env
    command: /bin/bash -c ./test.sh

  service:
    build: .
    env_file: ./dev.env
